// Mocks generated by Mockito
// Do not manually edit this file.

import 'dart:async' as _i3;
import 'package:connectivity_plus/connectivity_plus.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

class MockConnectivity extends _i1.Mock implements _i2.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.ConnectivityResult> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(#checkConnectivity, []),
        returnValue: _i3.Future<_i2.ConnectivityResult>.value(_i2.ConnectivityResult.none),
      ) as _i3.Future<_i2.ConnectivityResult>);

  @override
  _i3.Stream<_i2.ConnectivityResult> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i3.Stream<_i2.ConnectivityResult>.empty(),
      ) as _i3.Stream<_i2.ConnectivityResult>);
}
