name: flutter_ar_app
description: A Flutter AR application with layered architecture and internationalization.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management & Dependency Injection
  flutter_riverpod: ^2.4.9
  get_it: ^7.6.4
  injectable: ^2.3.2
  dartz: ^0.10.1

  # Networking & Data
  dio: ^5.4.0
  json_annotation: ^4.8.1
  flutter_cache_manager: ^3.3.1

  # Storage & Security
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # Media & AR
  video_player: ^2.8.1
  ar_flutter_plugin: ^0.7.3
  camera: ^0.10.5+5
  permission_handler: ^11.1.0
  equatable: ^2.0.5
  path_provider: ^2.1.1
  flutter_ffmpeg: ^0.4.2
  gallery_saver: ^2.3.2
  android_intent_plus: ^4.0.3
  media_scanner: ^2.1.0

  # UI & Utilities
  cupertino_icons: ^1.0.2
  go_router: ^12.1.3
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.4
  lottie: ^2.7.0

  # Environment Configuration
  flutter_dotenv: ^5.1.0

  # Internationalization
  intl: ^0.18.1
  
  # Firebase Cloud Messaging
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.7.4
  
  # Deep Links
  uni_links: ^0.5.1
  
  # Performance Monitoring
  battery_plus: ^5.0.2
  device_info_plus: ^9.1.1
  flutter_displaymode: ^0.6.0
  performance_monitor: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  
  # Testing
  mockito: ^5.4.4
  build_test: ^2.1.7

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/animations/
    - lib/l10n/
    - assets/l10n/

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
  output_localization_file: app_localizations.dart
  template_arb_file: app_en.arb
  output_class: AppLocalizations
